### ISSUE TITLE
Polling not successful

### ISSUE THREAD

**Issue by lexus440** [amaximus/pollen_hu#10]
```
pollens: []
provider: Data provided by antsz.hu
last_poll: 2023/09/10 22:46
successful_poll: 'false'
icon: mdi:blur
friendly_name: Pollen HU
```

Előző verziók még működtek, szépen jelezte is a kártyád a polleneket, de most nem sikerül lehívnia az adatokat. Nem tudom azóta mi változott.
Az összes pollent szeretném megjeleníteni, ami 0 érték feletti.

HACS-ról töltöttem le: 0.6.0 verziód

```
  - platform: pollen_hu
    all_dominant: true
#    name: 'Pollen adatok'
#    pollens:
 #    - Parlagfű
  #   - Alternaria
   #  - Csalánfélék
    # - Pázsitfűfélék
#     - Ciprusfélék és tiszafafélék
#     - Útifű
#     - Lórom
#     - Kenderfélék
#     - Disznóparéj- és libatopfélék
#     - Üröm
#     - Nyír
#     - Éger
#     - Mogyoró
#     - Kőris
#     - Nyár
#     - Szil
#     - Juhar
#     - Fűz
#     - Gyertyán
#     - Platán
#     - Tölgy
#     - Dió
#     - Bükk
#     - Eperfafélék
#     - Fenyőfélék
#     - Hárs
```

**Comment by amaximus** [comment]
A `successful_poll: false` arra utal, hogy az integráció nem tudta az ÁNTSZ oldalát elérni.
Amúgy az integráció nem támogatja, hogy a 0 fölötti pollenek adatai legyenek csak. Az `all_dominant: true` csak azt jelebti, hogy a legmagasabb szintű poleneket mind az attribútumba teszi, szemben a `false` értékkel amikor is csak az első ilyen pollent veszi figyelembe.

Most rendben jönnek az adatok:
![Screenshot_20230910-232904](https://github.com/amaximus/pollen_hu/assets/2511168/b89184dc-0b0f-4cc3-8526-2360b44a250c)

**Comment by lexus440** [comment]
Köszönöm szépen, hogy ilyen későn máris válaszoltál. Esetleg hol keressem a hibát?
A HA teljesen szabadon eléri az ántsz oldalát, nincs semmi tűzfalszabály.

**Comment by amaximus** [comment]
Nem feltétlenül a kliens gép az oka, az utóbbi időben többször volt az ÁNTSZ oldala elérhetetlen percekig. Meg kellene várni a következő update-et (ha jól emlékszem óránként próbál adatokat frissíteni).

**Comment by lexus440** [comment]
Még nem jöttem rá, hogy hol, de biztosan nálam van a hiba, ezért zárom. Köszi!

**Comment by amaximus** [comment]
Augusztus eleje óta az ÁNTSZ egy másik root-intermediate tanúsítványt használ amit hozzá kellene adni a CA store-hoz. Alternatvak;nt a szenzor definícióban az `ssl: false` kikapcsolja az SSL ellenörzést.
