### ISSUE TITLE
Dominant pollen list

### ISSUE THREAD

**Issue by Sygnus83** [amaximus/pollen_hu#6]
Szia!

Azt vettem észre, hogy pl most van 3 domináns pollen, de csak egyet emel ki közülük. Ilyenkor nem kéne mind a 3 db value: '3' -as felsorolva legyen a dominant pollen -nél  ?

- name: Nyír
  value: '3'
- name: Platán
  value: '3'
- name: Eperfafélék
  value: '3'

dominant_pollen_value: 3
dominant_pollen: Nyír

Köszi előre is !

**Comment by amaximus** [comment]
Eredetileg szándékos volt, hogy csak az elsőt vegye, de lévén igény keletkezett a teljes listára, adtam hozzá egy új paramétert és így a teljes listát is ki lehet nyerni.
Kérlek frissíts a 0.1.0 verzióra, állítsd be az új konfigrációs értéket és jelezz vissza.

**Comment by Sygnus83** [comment]
Szuper lett ! Köszönöm szépen !
